### En el taller 5 google collab estaba teniendo problemas con google drive entonces no pude hacerlo en django por que no me creaba el archivo .h5

![error de google drive!](/WhatsApp%20Image%202022-09-22%20at%2012.40.09%20AM.jpeg "error")

## Pero estas son las pruebas de que entrene el nuevo modelo en el google collab 
![prueba](/Screenshot%202022-09-22%20005231.png "modelo entrenado")
![prueba](/Screenshot%202022-09-22%20005230.png "modelo entrenado")